-- ============================================================================
-- Área de MISSÕES dos sócios (/missoes) — schema completo e IDEMPOTENTE.
-- Rode no Supabase: Dashboard → SQL Editor → New query → cole tudo → Run.
-- Pode rodar de novo quando quiser: tudo usa "if not exists" / "or replace".
-- ----------------------------------------------------------------------------
-- Como a segurança funciona aqui:
--
--  • LOGIN dos membros = Supabase Auth (e-mail + senha). Cada chamada do app
--    autenticado leva o JWT do membro, então o Postgres sabe quem é via
--    auth.uid(). As policies (RLS) abaixo usam isso.
--
--  • Dois tipos de missão na mesma tabela "Missoes":
--      - 'empresa'  → criadas SÓ por você (rota server-side com a SECRET key,
--                     protegida pela senha-mestra MISSOES_PASSWORD). Todo
--                     membro logado VÊ; o membro designado pode mover o
--                     STATUS da que é dele.
--      - 'propria'  → área privada de cada membro. Só o dono (Owner_id) lê e
--                     escreve. Ninguém mais enxerga.
--
--  • NOTIFICAÇÕES: um trigger insere uma linha em "Notificacoes" toda vez que
--    uma missão de empresa é atribuída/reatribuída a um membro.
-- ============================================================================


-- ─────────────────────────────────────────────────────────────────────────
-- 1) MEMBROS  (perfil espelhando auth.users — pra atribuir missões por nome)
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public."Membros" (
  id         uuid primary key references auth.users(id) on delete cascade,
  nome       text,
  email      text,
  papel      text not null default 'membro',   -- 'membro' | 'admin'
  criado_em  timestamptz default now()
);

alter table public."Membros" enable row level security;

-- Todo membro logado pode ler a lista (pra você atribuir e pra exibir nomes).
drop policy if exists "Membros leitura logada" on public."Membros";
create policy "Membros leitura logada" on public."Membros"
  for select to authenticated using (true);

-- Cada um cria/edita só o próprio perfil.
drop policy if exists "Membros escreve o proprio" on public."Membros";
create policy "Membros escreve o proprio" on public."Membros"
  for insert to authenticated with check (id = auth.uid());
drop policy if exists "Membros atualiza o proprio" on public."Membros";
create policy "Membros atualiza o proprio" on public."Membros"
  for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

-- Cria/atualiza o perfil automaticamente quando alguém se cadastra no Auth.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public."Membros" (id, nome, email)
  values (new.id, coalesce(new.raw_user_meta_data->>'nome', new.email), new.email)
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Backfill: cria perfil pra quem já tinha conta antes deste script.
insert into public."Membros" (id, nome, email)
select u.id, coalesce(u.raw_user_meta_data->>'nome', u.email), u.email
from auth.users u
on conflict (id) do nothing;


-- ─────────────────────────────────────────────────────────────────────────
-- 2) MISSOES  (cria se faltar; depois completa colunas/índices/defaults)
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public."Missoes" (
  id bigint generated by default as identity primary key,
  "Titulo" text not null,
  "Descricao" text,
  "Responsavel" text,
  "Status" text,
  "Prioridade" text,
  "Prazo" date,
  "Criado_em" timestamp with time zone
);

-- Colunas novas (idempotente):
alter table public."Missoes" add column if not exists "Tipo" text;             -- 'empresa' | 'propria'
alter table public."Missoes" add column if not exists "Responsavel_id" uuid;   -- a quem a de empresa foi atribuída
alter table public."Missoes" add column if not exists "Owner_id" uuid;         -- dono da missão própria
alter table public."Missoes" add column if not exists "Criado_por" text;       -- nome de quem criou

-- Defaults (idempotente; conserta linhas/tabela antigas):
alter table public."Missoes" alter column "Status"     set default 'pendente';   -- pendente | em-andamento | finalizado
alter table public."Missoes" alter column "Prioridade" set default 'media';      -- baixa | media | alta
alter table public."Missoes" alter column "Criado_em"  set default now();
alter table public."Missoes" alter column "Tipo"       set default 'empresa';
update public."Missoes" set "Tipo" = 'empresa' where "Tipo" is null;

create index if not exists missoes_status_idx    on public."Missoes" ("Status");
create index if not exists missoes_criado_em_idx on public."Missoes" ("Criado_em" desc);
create index if not exists missoes_tipo_idx       on public."Missoes" ("Tipo");
create index if not exists missoes_owner_idx      on public."Missoes" ("Owner_id");
create index if not exists missoes_resp_idx       on public."Missoes" ("Responsavel_id");

alter table public."Missoes" enable row level security;

-- Leitura: missões de empresa são visíveis a todos (inclusive anon, mantém
-- compatibilidade); missões próprias SÓ pro dono logado.
drop policy if exists "Missoes leitura publica" on public."Missoes";
drop policy if exists "Missoes leitura" on public."Missoes";
create policy "Missoes leitura" on public."Missoes"
  for select using (
    "Tipo" = 'empresa'
    or (auth.uid() is not null and "Owner_id" = auth.uid())
  );

-- Inserir missão própria: só o dono, e só do tipo 'propria'.
-- (As de empresa entram pela rota server-side com a SECRET key, que bypassa RLS.)
drop policy if exists "Missoes insere propria" on public."Missoes";
create policy "Missoes insere propria" on public."Missoes"
  for insert to authenticated
  with check ("Tipo" = 'propria' and "Owner_id" = auth.uid());

-- Atualizar: o dono mexe na própria; o designado mexe na de empresa que é dele.
drop policy if exists "Missoes atualiza" on public."Missoes";
create policy "Missoes atualiza" on public."Missoes"
  for update to authenticated
  using (
    ("Tipo" = 'propria' and "Owner_id" = auth.uid())
    or ("Tipo" = 'empresa' and "Responsavel_id" = auth.uid())
  )
  with check (
    ("Tipo" = 'propria' and "Owner_id" = auth.uid())
    or ("Tipo" = 'empresa' and "Responsavel_id" = auth.uid())
  );

-- Remover: só missão própria do dono. (Empresa só pela rota server-side.)
drop policy if exists "Missoes remove propria" on public."Missoes";
create policy "Missoes remove propria" on public."Missoes"
  for delete to authenticated
  using ("Tipo" = 'propria' and "Owner_id" = auth.uid());


-- ─────────────────────────────────────────────────────────────────────────
-- 3) NOTIFICACOES  (sino do membro)
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public."Notificacoes" (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users(id) on delete cascade,
  missao_id  bigint references public."Missoes"(id) on delete cascade,
  titulo     text not null,
  corpo      text,
  tipo       text not null default 'atribuida',  -- atribuida | status | ...
  lida       boolean not null default false,
  criado_em  timestamptz default now()
);

create index if not exists notif_user_idx on public."Notificacoes" (user_id, lida, criado_em desc);

alter table public."Notificacoes" enable row level security;

-- Cada membro vê e marca como lida só as próprias notificações.
drop policy if exists "Notif le as proprias" on public."Notificacoes";
create policy "Notif le as proprias" on public."Notificacoes"
  for select to authenticated using (user_id = auth.uid());
drop policy if exists "Notif atualiza as proprias" on public."Notificacoes";
create policy "Notif atualiza as proprias" on public."Notificacoes"
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
-- (Não há policy de INSERT: notificações nascem só pelo trigger abaixo,
--  que roda como security definer e bypassa RLS.)

-- Trigger: ao criar/atribuir uma missão de empresa a um membro, notifica.
create or replace function public.notify_missao_atribuida()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new."Tipo" = 'empresa'
     and new."Responsavel_id" is not null
     and (tg_op = 'INSERT' or new."Responsavel_id" is distinct from old."Responsavel_id")
  then
    insert into public."Notificacoes" (user_id, missao_id, titulo, corpo, tipo)
    values (
      new."Responsavel_id",
      new.id,
      'Nova missão pra você: ' || new."Titulo",
      coalesce(new."Descricao", ''),
      'atribuida'
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_notify_missao on public."Missoes";
create trigger trg_notify_missao
  after insert or update on public."Missoes"
  for each row execute function public.notify_missao_atribuida();


-- ─────────────────────────────────────────────────────────────────────────
-- 4) (OPCIONAL) marque você como admin depois de criar sua conta:
--    update public."Membros" set papel = 'admin' where email = 'mizaelneo@gmail.com';
-- ─────────────────────────────────────────────────────────────────────────
