-- Tabela das missões para os sócios (área /missoes do site de planejamento).
-- Rode este SQL uma vez no Supabase: Dashboard → SQL Editor → New query → Run.
-- É IDEMPOTENTE: pode rodar mesmo se a tabela já existir (ex: criada via
-- importação de CSV) — ele só completa o que faltar (defaults + RLS).
--
-- Segurança: a LEITURA é pública (o app lê do navegador com a publishable key),
-- mas a ESCRITA só acontece pela rota server-side com a SECRET key. Por isso
-- ligamos RLS, liberamos só SELECT, e NÃO criamos policy de insert/update/delete
-- (a publishable key fica sem permissão de escrita; a secret key bypassa RLS).
-- SEM ISSO, qualquer um com a URL do site consegue escrever direto no banco.

create table if not exists public."Missoes" (
  id bigint generated by default as identity primary key,
  "Titulo" text not null,
  "Descricao" text,
  "Responsavel" text,
  "Status" text,
  "Prioridade" text,
  "Prazo" date,
  "Criado_em" timestamp with time zone
);

-- Defaults (idempotente; conserta tabela criada sem eles):
alter table public."Missoes" alter column "Status" set default 'pendente';      -- pendente | em-andamento | finalizado
alter table public."Missoes" alter column "Prioridade" set default 'media';      -- baixa | media | alta
alter table public."Missoes" alter column "Criado_em" set default now();

create index if not exists missoes_status_idx     on public."Missoes" ("Status");
create index if not exists missoes_criado_em_idx  on public."Missoes" ("Criado_em" desc);

-- RLS: leitura pública, escrita só via secret key (server-side):
alter table public."Missoes" enable row level security;
drop policy if exists "Missoes leitura publica" on public."Missoes";
create policy "Missoes leitura publica" on public."Missoes" for select using (true);
